#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1534205742                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : assets/press-kit.zip                      # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Newst                                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Get your news faster.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Matan Mashraki
your_link                                 : https://matanmashraki.com
your_city                                 : Israel
contact_page                              : https://matanmashraki.com/contact
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : planecore
github_username                           : planecore
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Stories UI
    description                           : A series of stories with the latest news you care about.
    fontawesome_icon_name                 : mobile
    
  - title                                 : Fast Updates
    description                           : Newst updates its sources every few minutes.
    fontawesome_icon_name                 : fighter-jet

  - title                                 : Automatic Reader Mode
    description                           : Open articles automatically in Reader Mode to read without interruptions.
    fontawesome_icon_name                 : align-left

  - title                                 : Choose Topics
    description                           : Customize your feed to show topics that intrests you like science, sports and health.
    fontawesome_icon_name                 : hdd

  - title                                 : Local News
    description                           : Get the latest news in your city.
    fontawesome_icon_name                 : map-marker-alt
  
  - title                                 : Custom Search
    description                           : You can follow specific keywords that intrests you.
    fontawesome_icon_name                 : bookmark




# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
